# Generated by Django 3.1 on 2020-08-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-creacion'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-creacion'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creacion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Modificacion'),
        ),
        migrations.AddField(
            model_name='factura',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creacion'),
        ),
        migrations.AddField(
            model_name='factura',
            name='modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Modificacion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion'),
        ),
    ]
