# Generated by Django 3.1 on 2020-08-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0002_auto_20200809_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Modificacion'),
        ),
    ]
